namespace SamplyGame
{
	// Perhaps this file can be auto-generated by T4 script
	public static class Assets
	{
		public static class Materials
		{
			public const string Enemy1 = "Materials/Monkey.xml";
			public const string Enemy2 = "Materials/Enemy4DD.xml";
			public const string Enemy3 = "Materials/Enemy3.xml";
			public const string SmallPlate = "Materials/Enemy3weapon.xml";
			public const string Pyramid = "Materials/PyramidMaterial.xml";
			public const string Grass = "Materials/Grass.xml";
			public const string Player = "Materials/Player1D.xml";
			public const string Apple = "Materials/Apple.xml";
			public const string MachineGun = "Materials/MachineGun.xml";
		}

		public static class Models
		{
			public const string Tree = "Models/PyramidTree.mdl";
			public const string Box = "Models/Box.mdl";
			public const string Plane = "Models/Plane.mdl";
			public const string Player = "Models/Player1.mdl";
			public const string Enemy1 = "Models/Monkey.mdl";
			public const string Enemy2 = "Models/Enemy4.mdl";
			public const string Enemy3 = "Models/Enemy3.mdl";
			public const string SmallPlate = "Models/Enemy3weapon.mdl";
			public const string Coin = "Models/Apple.mdl";
		}

		public static class Particles
		{
			public const string Explosion = "Particles/Explosion.pex";
			public const string PlayerExplosion = "Particles/PlayerExplosion.pex";
			public const string HeavyMissileExplosion = "Particles/HeavyMissileExplosion.pex";
			public const string MissileTrace = "Particles/MissileTrace.pex";
		}

		public static class Sounds
		{
			public const string BigExplosion = "Sounds/BigExplosion.wav";
			public const string MachineGun = "Sounds/MachineGun.wav";
			public const string SmallExplosion = "Sounds/SmallExplosion.wav";
			public const string Powerup = "Sounds/Powerup.wav";
		}

		public static class Fonts
		{
			public const string Font = "Fonts/Font.ttf";
		}

		public static class PostProcess
		{
			public const string FXAA3 = "PostProcess/FXAA3.xml";
		}

		public static class Textures
		{
			public const string XamarinLogo = "Textures/xamarin.png";
		}
	}
}
